# Generated by Django 5.0.7 on 2024-08-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resend_link_flag', models.BooleanField(default=True)),
                ('activation_code', models.IntegerField(db_index=True, null=True)),
                ('is_activated', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('entity_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_value', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('agent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], max_length=10)),
                ('message_content', models.TextField()),
                ('message_status', models.CharField(default='Unread', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ticket_id', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=255, unique=True)),
                ('is_year_required', models.BooleanField(default=False)),
                ('is_reason_required', models.BooleanField(default=False)),
                ('is_entity_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxOrganizer',
            fields=[
                ('tax_organizer_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('basic_details_form', models.JSONField(blank=True, null=True)),
                ('dependents_details', models.JSONField(blank=True, null=True)),
                ('state_details', models.JSONField(blank=True, null=True)),
                ('income_details', models.JSONField(blank=True, null=True)),
                ('rental_details', models.JSONField(blank=True, null=True)),
                ('expenses_details', models.JSONField(blank=True, null=True)),
                ('entity_details', models.JSONField(blank=True, null=True)),
                ('shareholder_details', models.JSONField(blank=True, null=True)),
                ('balance_sheet_details', models.JSONField(blank=True, null=True)),
                ('link_form_details', models.JSONField(blank=True, null=True)),
                ('home_expenses_details', models.JSONField(blank=True, null=True)),
                ('business_formation_details', models.JSONField(blank=True, null=True)),
                ('basic_details_updated_at', models.DateTimeField(blank=True, null=True)),
                ('dependents_details_updated_at', models.DateTimeField(blank=True, null=True)),
                ('state_details_updated_at', models.DateTimeField(blank=True, null=True)),
                ('income_details_updated_at', models.DateTimeField(blank=True, null=True)),
                ('rental_details_updated_at', models.DateTimeField(blank=True, null=True)),
                ('expenses_details_updated_at', models.DateTimeField(blank=True, null=True)),
                ('entity_details_updated_at', models.DateTimeField(blank=True, null=True)),
                ('shareholder_details_updated_at', models.DateTimeField(blank=True, null=True)),
                ('balance_sheet_details_updated_at', models.DateTimeField(blank=True, null=True)),
                ('link_form_details_updated_at', models.DateTimeField(blank=True, null=True)),
                ('home_expenses_details_updated_at', models.DateTimeField(blank=True, null=True)),
                ('business_formation_details_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketFiles',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_id', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, null=True)),
                ('service_id', models.IntegerField(db_index=True, null=True)),
                ('service_year_value', models.IntegerField(db_index=True)),
                ('reason', models.TextField()),
                ('entity_value', models.IntegerField(db_index=True, null=True)),
                ('disable_chatbox', models.BooleanField(default=False)),
                ('disable_chatbox_updated_at', models.DateTimeField(blank=True, null=True)),
                ('tax_organizer_id', models.IntegerField(db_index=True, null=True)),
                ('invoice_id', models.IntegerField(blank=True, null=True)),
                ('invoice_id_updated_at', models.DateTimeField(blank=True, null=True)),
                ('ticket_status', models.CharField(max_length=50)),
                ('assignee_agent_name', models.CharField(blank=True, max_length=100, null=True)),
                ('assignee_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket_status_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearDropdown',
            fields=[
                ('service_year_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_year_value', models.IntegerField(null=True)),
            ],
        ),
    ]
