# Generated by Django 5.0.7 on 2024-08-01 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resend_link_flag', models.BooleanField(default=True)),
                ('activation_code', models.IntegerField(db_index=True, null=True)),
                ('is_activated', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, unique=True)),
                ('is_year_required', models.BooleanField(default=False)),
                ('is_reason_required', models.BooleanField(default=False)),
                ('is_entity_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_year_value', models.IntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('disable_chatbox', models.BooleanField(default=False)),
                ('tax_organiser_id', models.IntegerField(blank=True, null=True)),
                ('tax_draft_id', models.IntegerField(blank=True, null=True)),
                ('document_id', models.IntegerField(blank=True, null=True)),
                ('invoice_id', models.IntegerField(blank=True, null=True)),
                ('p_document_id', models.IntegerField(blank=True, null=True)),
                ('ticket_status', models.CharField(blank=True, max_length=50, null=True)),
                ('assigned_agent_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stl_apis.services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
